export const defaultRoadmap = [
  { id: 1, text: "# Phase 1: Fundamentals (Month 1 – 1.5)", completed: false },
  { id: 2, text: "Arrays & Strings", completed: false },
  { id: 3, text: "Basic Maths (GCD, LCM, Prime, Power, etc.)", completed: false },
  { id: 4, text: "Sorting (Bubble, Selection, Insertion, Merge, Quick)", completed: false },
  { id: 5, text: "Binary Search & Applications", completed: false },
  { id: 6, text: "Two Pointers / Sliding Window", completed: false },
  { id: 7, text: "# Phase 2: Core Data Structures (Month 2 – 3)", completed: false },
  { id: 8, text: "Hashing (Maps, Sets)", completed: false },
  { id: 9, text: "Stack & Queue (Next Greater, Balanced Parens, Monotonic Stack)", completed: false },
  { id: 10, text: "Linked List (Singly, Doubly, Reverse, Cycle Detection)", completed: false },
  { id: 11, text: "Recursion + Backtracking (Subset, Permutation, N-Queens)", completed: false },
  { id: 12, text: "# Phase 3: Trees & Heaps (Month 4)", completed: false },
  { id: 13, text: "Binary Trees (Traversal, Height, LCA, Mirror)", completed: false },
  { id: 14, text: "Binary Search Trees (Insert, Delete, Floor, Ceil)", completed: false },
  { id: 15, text: "Heaps & Priority Queue", completed: false },
  { id: 16, text: "Tries (Autocomplete)", completed: false },
  { id: 17, text: "# Phase 4: Graphs + Advanced Concepts (Month 5–6)", completed: false },
  { id: 18, text: "Graph Representations (BFS, DFS)", completed: false },
  { id: 19, text: "Cycle Detection, Topological Sort", completed: false },
  { id: 20, text: "Shortest Path (Dijkstra, Bellman-Ford, Floyd-Warshall)", completed: false },
  { id: 21, text: "Union-Find / DSU", completed: false },
  { id: 22, text: "Bit Manipulation (XOR tricks, Bitmask DP)", completed: false },
  { id: 23, text: "# Phase 5: DP + Practice + Patterns (Month 7–8)", completed: false },
  { id: 24, text: "1D DP: Fibonacci, Climb Stairs, Min Cost", completed: false },
  { id: 25, text: "2D DP: Grid, Knapsack, Subset Sum", completed: false },
  { id: 26, text: "String DP: LCS, Edit Distance, Palindromes", completed: false },
  { id: 27, text: "DP on Trees, DP on Bitmask (optional)", completed: false },
  { id: 28, text: "# Phase 6: Final Prep + Mocks (Month 9)", completed: false },
  { id: 29, text: "Solve 10–15 Company-specific sets", completed: false },
  { id: 30, text: "Mock interviews (Pramp / InterviewBuddy)", completed: false },
  { id: 31, text: "Revise 50 key problems (Arrays, Recursion, Graph, DP)", completed: false },
  { id: 32, text: "Participate in Contests (LeetCode Weekly, Codeforces)", completed: false },
];
